### ISSUE TITLE
permission denied when running lxd init (mastering tutorial)

### ISSUE THREAD

**Issue by gruyaume** [canonical/charmed-aether-sd-core#62]
### Bug Description

The documentation points to running `lxd init --auto` but I get permission denied. The user has to be added to the lxd group. 

### To Reproduce

1. `lxd init --auto`

### Environment

- Ubuntu 24.04
- LXD: 5.21/stable

### Relevant log output

```shell
ubuntu@canonical:~$ lxd init --auto
Error: Failed to connect to local LXD: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: permission denied
```

**Comment by gruyaume** [comment]
Adding the following commands should do the job:
```
ubuntu@canonical:~/charmed-aether-sd-core/terraform$ sudo usermod -aG lxd "$USER"
ubuntu@canonical:~/charmed-aether-sd-core/terraform$ newgrp lxd
```

**Comment by patriciareinoso** [comment]
oh but this actually failed https://github.com/canonical/charmed-aether-sd-core/issues/63 
 and what you suggested fixed it :+1:
