### ISSUE TITLE
Multus Link not found errors when  adding container to network (Mastering Tutorial)

### ISSUE THREAD

**Issue by gruyaume** [canonical/charmed-aether-sd-core#70]
### Bug Description

I am following the mastering tutorial and I am unable to [deploy the user-plane](https://canonical-charmed-aether-sd-core.readthedocs-hosted.com/en/latest/tutorials/mastering/#deploy-sd-core-user-plane). I'm getting Multus errors and the upf pod stays in `Init`, it never goes to `Running`

### To Reproduce

Follow the mastering tutorial

### Environment

- Juju: 3.5.5
- MicroK8s v1.31.3 revision 7448
- LXD: 5.21.2 LTS

### Relevant log output

```shell
Warning  FailedCreatePodSandBox  16s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5d2a343f658ddb571ec13e7234c91b206c7532e19de8432a136e202a3f03817e": plugin type="multus" name="multus-cni-network" failed (add): [user-plane/upf-0/69902b92-240e-42e5-b5ad-ccfddcbba7e6:access-net]: error adding container to network "access-net": Link not found



ubuntu@user-plane:~$ microk8s.kubectl get pods -n user-plane
NAME                             READY   STATUS     RESTARTS   AGE
grafana-agent-0                  2/2     Running    0          3m19s
modeloperator-5496644fc6-mlfhg   1/1     Running    0          4m
upf-0                            0/3     Init:0/1   0          76s



ubuntu@juju-controller:/home/ubuntu/terraform$ juju status
Model       Controller  Cloud/Region                  Version  SLA          Timestamp
user-plane  sdcore      user-plane-cluster/localhost  3.5.5    unsupported  14:18:40Z

App            Version  Status   Scale  Charm              Channel        Rev  Address         Exposed  Message
grafana-agent  0.40.4   blocked      1  grafana-agent-k8s  latest/stable   80  10.152.183.184  no       Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-wr...
upf            1.5.0    waiting    0/1  sdcore-upf-k8s     1.5/stable     715  10.152.183.100  no       Waiting for Multus to be ready

Unit              Workload  Agent  Address      Ports  Message
grafana-agent/0*  blocked   idle   10.1.36.247         Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-wr...
upf/0             unknown   lost                       agent lost, see 'juju show-status-log upf/0'

Offer         Application  Charm           Rev  Connected  Endpoint  Interface  Role
upf-fiveg-n3  upf          sdcore-upf-k8s  715  0/0        fiveg_n3  fiveg_n3   provider
upf-fiveg-n4  upf          sdcore-upf-k8s  715  0/0        fiveg_n4  fiveg_n4   provider
```

**Comment by ghislainbourgeois** [comment]
Quick question, I see that you listed Juju 3.5.5 but the documentation mentions 3.6, was this a voluntary deviation? I do not think it is related, but more information is better.

Also, do you see anything interesting in the logs of the multus pods?

**Comment by gruyaume** [comment]
I initially switched to Juju 3.5 because of #64. 

Actually I don't see the multus pod in `kube-system`. I may have forgotten to install it, or maybe the installation failed. I'll validate.

**Comment by gruyaume** [comment]
Yeah this was definitely a user error. I missed the command to install Multus.


That being said, we should probably have the upf go to blocked status when Multus is not enabled with the proper error message. This issue may happen to other users.

**Comment by ghislainbourgeois** [comment]
Yes, looking at the charm code, it is supposed to do exactly that, but the library implementation does not check the right thing. I will close this issue in favor of this one: https://github.com/canonical/kubernetes-charm-libraries/issues/75
